//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuffle_n_queue.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuffle_n_queue.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string AboutButtonCredits {
            get {
                return ResourceManager.GetString("AboutButtonCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutButtonEmail {
            get {
                return ResourceManager.GetString("AboutButtonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to home.
        /// </summary>
        public static string AboutButtonPin {
            get {
                return ResourceManager.GetString("AboutButtonPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string AboutButtonReview {
            get {
                return ResourceManager.GetString("AboutButtonReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string AboutButtonStore {
            get {
                return ResourceManager.GetString("AboutButtonStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string AboutButtonTwitter {
            get {
                return ResourceManager.GetString("AboutButtonTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super simple music player to play the music and playlists on your device, shuffled..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All songs.
        /// </summary>
        public static string AllSongsHeader {
            get {
                return ResourceManager.GetString("AllSongsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your music shuffled.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put a calendar on your home screen.
        /// </summary>
        public static string OtherAppsCalendarTileDescription {
            get {
                return ResourceManager.GetString("OtherAppsCalendarTileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Tile.
        /// </summary>
        public static string OtherAppsCalendarTileName {
            get {
                return ResourceManager.GetString("OtherAppsCalendarTileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other apps.
        /// </summary>
        public static string OtherAppsHeader {
            get {
                return ResourceManager.GetString("OtherAppsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a map of your location to your friends.
        /// </summary>
        public static string OtherAppsMeetMeHereDescription {
            get {
                return ResourceManager.GetString("OtherAppsMeetMeHereDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Me Here.
        /// </summary>
        public static string OtherAppsMeetMeHereName {
            get {
                return ResourceManager.GetString("OtherAppsMeetMeHereName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make comics with your camera phone.
        /// </summary>
        public static string OtherAppsToonifyDescription {
            get {
                return ResourceManager.GetString("OtherAppsToonifyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toonify.
        /// </summary>
        public static string OtherAppsToonifyName {
            get {
                return ResourceManager.GetString("OtherAppsToonifyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record, map and share your favorite trails.
        /// </summary>
        public static string OtherAppsTrailMapperDescription {
            get {
                return ResourceManager.GetString("OtherAppsTrailMapperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Mapper.
        /// </summary>
        public static string OtherAppsTrailMapperName {
            get {
                return ResourceManager.GetString("OtherAppsTrailMapperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-frills, no distractions music player.
        /// </summary>
        public static string OtherAppsYourMusicShuffledDescription {
            get {
                return ResourceManager.GetString("OtherAppsYourMusicShuffledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Music Shuffled.
        /// </summary>
        public static string OtherAppsYourMusicShuffledName {
            get {
                return ResourceManager.GetString("OtherAppsYourMusicShuffledName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
